In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
meta_data = pd.read_csv('Data/meta_data.csv')

In [3]:
meta_data

ID   ACTIVATED IN_REPAIR_SYSTEM  STILL_ALIVE  Lifetime
0        0   1/31/2019              NaN         True       593
1        1   12/4/2018              NaN         True       651
2        2   4/18/2019              NaN         True       516
3        3    3/5/2019              NaN         True       560
4        4   12/6/2018              NaN         True       649
...    ...         ...              ...          ...       ...
1022  1022   11/3/2018        9/11/2020        False       678
1023  1023  12/28/2018         6/3/2020        False       523
1024  1024   1/10/2019        6/11/2020        False       518
1025  1025    9/5/2018         2/9/2020        False       522
1026  1026   1/17/2019        9/18/2020        False       610

[1027 rows x 5 columns]

In [4]:
meta_data.describe()

ID     Lifetime
count  1027.000000  1027.000000
mean    513.000000   531.314508
std     296.613666    92.324199
min       0.000000   401.000000
25%     256.500000   453.000000
50%     513.000000   519.000000
75%     769.500000   592.500000
max    1026.000000   761.000000

In [5]:
# Number of Batteries.
N = 1027

In [13]:
def data(N):
    data = []
    
    path = f"{N}.npz"
    path = os.path.join("Data/npz/", path)
    
    bat_files = np.load(path)
    bat_files.files
    
    for bat_file in bat_files['arr_0']:
        data.append(bat_file)
    
    return data

In [14]:
data = data(N = 100)

In [15]:
data

[array([1.53609477e+09, 0.00000000e+00, 1.31999084e+01, 3.43739986e+01]),
 array([1.53609537e+09, 0.00000000e+00, 1.32050355e+01, 3.42481117e+01]),
 array([ 1.53609597e+09, -2.05996796e-03,  1.32050355e+01,  3.42481117e+01]),
 array([ 1.53609657e+09, -2.05996796e-03,  1.31999084e+01,  3.42481117e+01]),
 array([1.53609717e+09, 2.05996796e-03, 1.31947814e+01, 3.41245136e+01]),
 array([1.53609777e+09, 0.00000000e+00, 1.31898985e+01, 3.41245136e+01]),
 array([1.53609837e+09, 0.00000000e+00, 1.31898985e+01, 3.41245136e+01]),
 array([1.53609897e+09, 2.05996796e-03, 1.31847715e+01, 3.39986267e+01]),
 array([ 1.53609957e+09, -2.05996796e-03,  1.31847715e+01,  3.38727398e+01]),
 array([1.53610017e+09, 2.05996796e-03, 1.31798886e+01, 3.38727398e+01]),
 array([1.53610077e+09, 0.00000000e+00, 1.31747616e+01, 3.37491417e+01]),
 array([ 1.53610137e+09, -2.05996796e-03,  1.31747616e+01,  3.37491417e+01]),
 array([1.53610197e+09, 0.00000000e+00, 1.31698787e+01, 3.37491417e+01]),
 array([1.53610257e+09

In [16]:
len(data)

708835